// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/update_metrics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpdateMetrics_UpdateMetrics_FullMethodName = "/protocol.UpdateMetrics/UpdateMetrics"
)

// UpdateMetricsClient is the client API for UpdateMetrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateMetricsClient interface {
	UpdateMetrics(ctx context.Context, in *UpdateMetricsRequest, opts ...grpc.CallOption) (*UpdateMetricsResponse, error)
}

type updateMetricsClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateMetricsClient(cc grpc.ClientConnInterface) UpdateMetricsClient {
	return &updateMetricsClient{cc}
}

func (c *updateMetricsClient) UpdateMetrics(ctx context.Context, in *UpdateMetricsRequest, opts ...grpc.CallOption) (*UpdateMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMetricsResponse)
	err := c.cc.Invoke(ctx, UpdateMetrics_UpdateMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateMetricsServer is the server API for UpdateMetrics service.
// All implementations must embed UnimplementedUpdateMetricsServer
// for forward compatibility.
type UpdateMetricsServer interface {
	UpdateMetrics(context.Context, *UpdateMetricsRequest) (*UpdateMetricsResponse, error)
	mustEmbedUnimplementedUpdateMetricsServer()
}

// UnimplementedUpdateMetricsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdateMetricsServer struct{}

func (UnimplementedUpdateMetricsServer) UpdateMetrics(context.Context, *UpdateMetricsRequest) (*UpdateMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMetrics not implemented")
}
func (UnimplementedUpdateMetricsServer) mustEmbedUnimplementedUpdateMetricsServer() {}
func (UnimplementedUpdateMetricsServer) testEmbeddedByValue()                       {}

// UnsafeUpdateMetricsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateMetricsServer will
// result in compilation errors.
type UnsafeUpdateMetricsServer interface {
	mustEmbedUnimplementedUpdateMetricsServer()
}

func RegisterUpdateMetricsServer(s grpc.ServiceRegistrar, srv UpdateMetricsServer) {
	// If the following call pancis, it indicates UnimplementedUpdateMetricsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpdateMetrics_ServiceDesc, srv)
}

func _UpdateMetrics_UpdateMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateMetricsServer).UpdateMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateMetrics_UpdateMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateMetricsServer).UpdateMetrics(ctx, req.(*UpdateMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpdateMetrics_ServiceDesc is the grpc.ServiceDesc for UpdateMetrics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateMetrics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.UpdateMetrics",
	HandlerType: (*UpdateMetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateMetrics",
			Handler:    _UpdateMetrics_UpdateMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/update_metrics.proto",
}
